name: linter-check
on: push
jobs:
  linter-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: 'install'
        run: npm ci

      - name: 'start linter'
        run: make lint
